spring:
  datasource:
    url: jdbc:${DB_BASE}://${DB_SERVER}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


eureka:
  client:
    serviceUrl:
      # Явное указание маршрута к серверу Eureka с использованием IP-адреса
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      enabled: true
  instance:
    preferIpAddress: true
    # Установка интервала отправки эхо-запроса на сервер в 35 секунд
    lease-renewal-interval-in-seconds: 35