spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stackover_resource_service?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: postgres
    password: root

eureka:
  client:
    service-url:
      defaultZone: https://eureka:8761/eureka/