spring:
  datasource:
    url: jdbc:${DB_BASE}://${DB_SERVER}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


eureka:
  client:
    service-url:
      defaultZone: https://eureka:8761/eureka/